times = ('Palmeiras', 'Corinthians', 'Atlético-MG', 'Fluminense', 'Athletico-PR', 'Flamengo', 'Internacional', 'Bragantino', 'São Paulo', 'Santo', 'Botafogo', 'Ceará SC', 'Goiáis', 'Avaí', 'Cuibá', 'Coritiba', 'Améria-MG', 'Atlético-GO', 'Fortaleza', 'Juventude')
print('-=' * 20)
print('Lista dos times do Brasileirão:{}'.format(times))
print('-=' * 20)
print(f'Os 5 primeiros times são:{times[0:5]}')
print('-=' * 20)
print(f'Os 4 últimos times são: {times[16:20]}')
print('-=' * 20)
print(f'Os times em ordem alfabética são: {sorted(times)}')
print('-=' * 20)
print(f'O Corinthians está na {times.index("Corinthians")+1}º posição')
