num = list()
n1 = int(input('Digite um valor: '))
num.append(n1)
print('Adicionado ao final da lista...')
n2 = int(input('Digite um valor: '))
num.insert(0,n2)
print('Adicionado na posição 0...')
n3 = int(input('Digite um valor: '))
num.insert(1,n3)
print('Adicionado na posição 1...')
n4 = int(input('Digite um valor: '))
num.append(n4)
print('Adicionado no final da lista...')
n5 = int(input('Digite um valor: '))
num.insert(0,n5)
print('Adicionado no valor 0')
print('-=' * 30)
num.sort()
print(f'Os valores digitados em ordem foram {num}')
